version: 2.1

orbs:
  node: circleci/node@4.1.0
  jira: circleci/jira@1.2.2
jobs: 

  test_1:
    docker:
      - image: cimg/node:12.16
    steps:
      - checkout
      - node/install-packages: 
          override-ci-command: npm install
      - run:
          name: Install unitjs
          command: npm install unit.js
      - run:   
          command: npm install --save-dev jest
      - run:
          command: npm run test

  test_2:
    docker:
      - image: cimg/node:12.16
    steps:
      - checkout
      - node/install-packages:
          
          override-ci-command: npm install
      - run:
          name: Install jest
          command: npm install --save-dev jest
      - run: 
          command: npm run test   


  build:
    docker:
      - image: circleci/node:8

    working_directory: ~/CircleCI200
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json"}}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json"}}

          run: npm test


workflows:
  version: 2.1

  build-test:
    jobs:
      - build:
          post-steps:
            - jira/notify
      - cache-dependencies:
          requires:
            - build
            
      - test_1:
          requires:
            - build

      - test_2:
          requires:
            - build